### ISSUE TITLE
Restart H2O cluster on failure

### ISSUE THREAD

**Issue by Pscheidl** [h2oai/h2o-kubernetes#24]

**Comment by ICESDHR** [comment]
Is there any update?

**Comment by Pscheidl** [comment]
> Is there any update?

Hello @ICESDHR. No, no progress so far.

Didn't have time to finish this yet, but I sure can. @michalkurka is the team lead, tagging him to get any input on this - is this a priority now ? 

A simple restart, without checkpoints, should be doable rather quickly as an open source contribution.

**Comment by michalkurka** [comment]
@ICESDHR no update yet, it is currently not on our roadmap to implement this feature
